# Generated by Django 3.2 on 2022-11-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproduct')),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('heat_level', models.CharField(default=0, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('products.baseproduct',),
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproduct')),
                ('time_to_maturity', models.CharField(blank=True, max_length=140, null=True)),
                ('flavour', models.CharField(blank=True, max_length=140, null=True)),
                ('scovilles', models.CharField(blank=True, max_length=140, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('products.baseproduct',),
        ),
        migrations.CreateModel(
            name='SeedBox',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproduct')),
                ('price', models.ManyToManyField(to='products.ProductSizes')),
                ('seeds', models.ManyToManyField(to='products.Seed')),
            ],
            options={
                'verbose_name_plural': 'Seed Boxes',
            },
            bases=('products.baseproduct',),
        ),
        migrations.CreateModel(
            name='SauceBox',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproduct')),
                ('price', models.ManyToManyField(to='products.ProductSizes')),
                ('sauces', models.ManyToManyField(to='products.Sauce')),
            ],
            options={
                'verbose_name_plural': 'Sauce Boxes',
            },
            bases=('products.baseproduct',),
        ),
    ]
