# Generated by Django 3.2 on 2022-11-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saucebox',
            old_name='price',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='seedbox',
            old_name='price',
            new_name='sizes',
        ),
    ]
